accounts/urls.py
from django.urls import path

from .views import RegistrationFormView, LoginFormView, logout_view


app_name = "accounts"

urlpatterns = [
    path('registration/', RegistrationFormView.as_view(), name='registration'),
    path('authentication/', LoginFormView.as_view(), name='login'),
    path('logout/', logout_view, name='logout')
]

books/urls.py
from django.urls import path, include
from django.shortcuts import redirect

from . import views


app_name = "books"

urlpatterns = [
    path('', views.render_choice, name='choice'),
    path('active_books/', views.render_books_active, name='active-books'),
    path('take_book/<int:book_id>/', views.take_book, name='take-book'),
    path('arrears/', views.render_return_book, name='arrears'),
    path('return_book/<int:book_id>/', views.return_book, name='return-book')
]

library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from books.views import index
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('accounts/', include('accounts.urls')),
    path('choice/', include('books.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT, related_name='account', verbose_name='Пользователь')
    patronymic = models.CharField(max_length=200, verbose_name='Отчество')
    image = models.ImageField(default='', verbose_name='Изображение')
    short_description = models.TextField(null=True, blank=True, verbose_name='Краткое описание')

    def __str__(self) -> str:
        return f'{self.user.last_name} {self.user.first_name}'

books/models.py
from django.db import models
from django.utils import timezone

from accounts.models import Account


class Author(models.Model):
    first_name = models.CharField(max_length=200, verbose_name='Имя')
    last_name = models.CharField(max_length=200, verbose_name='Фамилия')

    def __str__(self) -> str:
        return f'{self.first_name} {self.last_name}'


class Book(models.Model):
    is_active = models.BooleanField(default=True, verbose_name='Может быть выдана')
    code = models.IntegerField(blank=True, null=True, verbose_name='Код книги')
    title = models.CharField(max_length=200, verbose_name='Название')
    image = models.ImageField(null=True, default='', verbose_name='Изображение')
    author = models.ForeignKey(
        Author, 
        on_delete=models.CASCADE, 
        related_name='books', 
        verbose_name='Автор')
    
    def __str__(self) -> str:
        return self.title


class Booking(models.Model):
    book = models.ForeignKey(Book, on_delete=models.PROTECT, related_name='bookings', verbose_name='Книга')
    reader = models.ForeignKey(Account, on_delete=models.PROTECT, related_name='bookings', verbose_name='Читатель')
    taking_at = models.DateTimeField(default=timezone.now(), verbose_name='Дата взятия книги')
    return_at = models.DateTimeField(null=True, blank=True, verbose_name='Дата возврата книги')

    def __str__(self) -> str:
        return f'{self.reader.user.last_name} {self.reader.user.first_name} {self.book.code}'

accounts/forms.py
from django import forms


class RegistrationForms(forms.Form):
    username = forms.CharField(max_length=200, label='Никнейм')
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={
            'class': 'form-control',
            'placeholder': 'Введите пароль'
        }),
        label='Пароль')
    first_name = forms.CharField(max_length=200, label='Имя')
    last_name = forms.CharField(max_length=200, label='Фамилия')
    patronymic = forms.CharField(max_length=200, label='Отчество', required=False)


class LoginForms(forms.Form):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    

accounts/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

from .forms import RegistrationForms, LoginForms
from .models import Account


class RegistrationFormView(View):
    form_class = RegistrationForms
    initial = {'key': 'value'}
    template_name = 'registration.html'

    def get(self, request, *args, **kwargs):
        form = RegistrationForms()

        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = RegistrationForms(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            patronymic = form.cleaned_data.get('patronymic')

            user = User.objects.create_user(
                username=username,
                password=password,
                first_name=first_name,
                last_name=last_name)

            Account.objects.get_or_create(
                user=user,
                patronymic=patronymic,
            )
            
            return redirect('index')

        return render(request, self.template_name, {'form': form})
    

class LoginFormView(View):
    form_class = LoginForms
    initial = {'key': 'value'}
    template_name = 'login.html'

    def get(self, request, *args, **kwargs):
        form = LoginForms()
        
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = LoginForms(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)

            if user and user.is_active:
                login(request, user)
                return redirect('books:choice')
            
            return redirect('index')

        return render(request, self.template_name, {'form': form})


def logout_view(request):
    logout(request)

    return redirect('index')

books/views.py
from django.db import transaction
from django.shortcuts import render, redirect
from django.utils import timezone

from .models import Book, Booking
from accounts.models import Account


def index(request):
    context = {
        'readers': Account.objects.all()
    }

    return render(request, template_name='index.html', context=context)


def render_choice(request):
    return render(request, template_name='choice.html')


def render_books_active(request):
    context = {
        'books': Book.objects.filter(is_active=True)
    }
    
    return render(request, template_name='books_active.html', context=context)


def take_book(request, book_id):
    with transaction.atomic():
        book = Book.objects.get(id=book_id)
        reader = Account.objects.get(user=request.user)
        Booking.objects.create(book=book, reader=reader)
        book.is_active = False
        book.save()

    return redirect('books:choice')
    

def render_return_book(request):
    reader = Account.objects.get(user=request.user)
    
    context = {
        'bookings': reader.bookings.filter(return_at=None)
    }

    return render(request, template_name='return_book.html', context=context)


def return_book(request, book_id):
    with transaction.atomic():
        book = Book.objects.get(id=book_id)
        reader = Account.objects.get(user=request.user)
        Booking.objects.filter(book=book, reader=reader, return_at=None).update(return_at=timezone.now())
        book.is_active = True
        book.save()

    return redirect('books:choice')

accounts/templates/login.html
{% extends "base.html" %}
{% load static %}
{% block style %}
<link rel="shortcut icon" href="{% static 'images/icon.jpg' %}" type="image/png">
<link rel="stylesheet" href="{% static 'styles/base.css' %}"/>
<link rel="stylesheet" href="{% static 'styles/accounts.css' %}"/>
{% endblock style %}
{% block title %}login{% endblock title %}
{% block content %}
<span class="text">Авторизация</span><br>
<div class="container">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><button type="submit">Войти</button></p>
  </form>
</div>
{% endblock content %}

accounts/templates/registration.html
{% extends "base.html" %}
{% load static %}
{% block style %}
<link rel="shortcut icon" href="{% static 'images/icon.jpg' %}" type="image/png">
<link rel="stylesheet" href="{% static 'styles/base.css' %}"/>
<link rel="stylesheet" href="{% static 'styles/accounts.css' %}"/>
{% endblock style %}
{% block title %}registration{% endblock title %}
{% block content %}
<span class="text">Регистрация</span><br>
<div class="container">
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Отправить</button>
  </form>
</div>
{% endblock content %}

books/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block style %}
  {% endblock style %}
  <title>{% block title %}Default title{% endblock title %}</title>
</head>
<body>
  <div class="title">LIBRARY</div>
  <br>
  {% block content %}
  {% endblock content %}
</body>
</html>

books/templates/books_active.html
{% extends "base.html" %}
{% load static %}
{% block style %}
<link rel="shortcut icon" href="{% static 'images/icon.jpg' %}" type="image/png">
<link rel="stylesheet" href="{% static 'styles/base.css' %}"/>
<link rel="stylesheet" href="{% static 'styles/books.css' %}"/>
<link rel="stylesheet" href="{% static 'styles/button.css' %}"/>
{% endblock style %}
{% block title %}active books{% endblock title %}
{% block content %}
<div class="return">
  <div class="button" id="button-3">
    <div id="circle"></div>
    <a href="{% url 'books:choice' %}">Вернуться</a>
  </div>
</div><br>
<div class="conteiner">
  {% for book in books %}
  <div class="book" id="{{ book.id }}" style="height: 500px;">
    <div class="image" style="display: flex; justify-content: center;">
      {% if book.image %}
      <img src="{{ book.image.url }}" style="height: 350px;">
      {% else %}
      <img src="{% static 'images/missingbook.jpeg' %}" style="height: 350px;">
      {% endif %}
    </div>
    <span>Название: {{book.title}}</span> 
    <br>
    <span>Код книги: {{book.code}}</span>
    <br>
    <div class="button" id="button-3">
      <div id="circle"></div>
      <a href="{% url 'books:take-book' book_id=book.id %}">Взять</a>
    </div>
    </div>
  {% endfor %}
</div>
{% endblock content %}

books/templates/choice.html
{% extends "base.html" %}
{% load static %}
{% block style %}
<link rel="shortcut icon" href="{% static 'images/icon.jpg' %}" type="image/png">
<link rel="stylesheet" href="{% static 'styles/base.css' %}"/>
<link rel="stylesheet" href="{% static 'styles/button.css' %}"/>
{% endblock style %}
{% block title %}choice{% endblock title %}
{% block content %}
<div class="conteiner">
  <div class="button" id="button-3">
    <div id="circle"></div>
    <a href="{% url 'books:active-books' %}">Взять книгу</a>
  </div>
  <div class="button" id="button-3">
    <div id="circle"></div>
    <a href="{% url 'books:arrears' %}">Вернуть книгу</a>
  </div>
  <div class="button" id="button-3">
    <div id="circle"></div>
    <a href="{% url 'accounts:logout' %}">Завершить сеанс</a>
  </div>
</div>
{% endblock content %}

books/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block style %}
<link rel="shortcut icon" href="{% static 'images/icon.jpg' %}" type="image/png">
<link rel="stylesheet" href="{% static 'styles/base.css' %}"/>
<link rel="stylesheet" href="{% static 'styles/index.css' %}"/>
<link rel="stylesheet" href="{% static 'styles/button.css' %}"/>
{% endblock style %}
{% block title %}readers{% endblock title %}
{% block content %}
<span class="text">Список читателей</span><br>
<div class="add">
  <div class="button" id="button-3">
    <div id="circle"></div>
    <a href="{% url 'accounts:registration' %}">Добавить</a>
  </div>
</div><br>
<div class="conteiner">
  {% for reader in readers %}
  <div class='reader' id="{{reader.id}}">
    {{ reader.user.last_name }}<br> 
    {{ reader.user.first_name }}<br>
    {{ reader.patronymic }}<br>
    {% if reader.short_description %}
      {{ reader.short_description }}<br>
    {% endif %}
    <div class="button" id="button-3">
      <div id="circle"></div>
      <a href="{% url 'accounts:login' %}">Перейти</a>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}

books/templates/readers.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>readers</title>
</head>
<body>
    <h2>Читатели</h2>
    <div>
        {% for reader in readers %}
            <p>{{ reader.last_name }} {{ reader.first_name }} {{ reader.patronymic }} <button><a href="/choice">Перейти</a></button></p>
        {% endfor %}
    </div>
</body>
</html>

books/templates/return_book.html
{% extends "base.html" %}
{% load static %}
{% block style %}
<link rel="shortcut icon" href="{% static 'images/icon.jpg' %}" type="image/png">
<link rel="stylesheet" href="{% static 'styles/base.css' %}"/>
<link rel="stylesheet" href="{% static 'styles/books.css' %}"/>
<link rel="stylesheet" href="{% static 'styles/button.css' %}"/>
{% endblock style %}
{% block title %}arrears{% endblock title %}
{% block content %}
{% if books %}
  <span class="text">Книги которые можно вернуть</span><br>
{% else %}
  <span class="text">У вас нет долгов</span><br>
{% endif %}
<div class="return">
  <div class="button" id="button-3">
    <div id="circle"></div>
    <a href="{% url 'books:choice' %}">Вернуться</a>
  </div>
</div><br>
<div class="conteiner">
  {% for booking in bookings %}
  <div class="book" id="{{ book.id }}">
    <div class="image" style="display: flex; justify-content: center;">
      {% if booking.book.image %}
      <img src="{{ booking.book.image.url }}" style="height: 350px;">
      {% else %}
      <img src="{% static 'images/missingbook.jpeg' %}" style="height: 350px;">
      {% endif %}
    </div>
    <span>Название: {{booking.book.title}}</span> 
    <br>
    <span>Код книги: {{booking.book.code}}</span>
    <br>
    <div class="button" id="button-3">
      <div id="circle"></div>
      <a href="{% url 'books:return-book' book_id=booking.book.id %}">Вернуть</a>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock content %}